project:
  type: website
  output-dir: docs

website:

  page-navigation: true
  reader-mode: true
  title: "ITM237"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus


  page-footer:
    left: |
      This website is built with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=80px}](https://quarto.org/).
    right: "&copy; Copyright 2022, Prajjwal K. Panday"     
      
  sidebar: 
    logo: "images/logo.jpg"
    pinned: false
    align: center
    tools:
      - icon: github
        href: https://github.com/prajjwalpanday/itm237
    style: "floating"
    search: true
    collapse-level: 1
    
    contents:
      - section: "**Course Information**"
        contents:
          - href: instructor.qmd
          - href: syllabus.qmd
      - section: "**Resources for Students**"
        contents:
          - href: resources/students/student_resources.qmd
            text: Resources for Students
          - href: resources/students/student_setup.qmd
            text: Intial Setup
      - section: "**Lecture Materials**"
        contents:
          - href: lecture1.qmd
            text: Lecture 1
          - href: lecture2.qmd 
          - href: lecture3.qmd 
          - href: lecture4.qmd 
          - href: lecture5.qmd 
          - href: publish.qmd
          - href: rgit.qmd
      - section: "**Assignments**"
        contents:
          - href: assignments/assignment_1.qmd
      - section: "**Final Project**"
        contents: 
          - href: assignments/final_project.qmd
          

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: tango

editor: visual

