---
title: "Lecture 1"
---

### Materials:

-   [Slides](/slides/slide_1.qmd)
-   [Code worksheet](/notebooks/code_1.ipynb)

#### What is Python?

A general-purpose programming language by Guido van Rossum <br> Intuitive and minimal coding <br> Interpreted not compiled <br> Dynamically typed, no type declarations, data type is tracked at runtime <br> Automatic memory management <br> Spacing defines blocks of code such as control structures and blocks <br>

#### Why Python?

-   Advantages
-   Ease of programming
-   Minimal time to develop and maintain codes
-   Modular and object-oriented
-   Large standard and user-contributed libraries
-   Large user community

### Running Code in the Interactive Shell or Line

Python is an interpreted language and you can run simple Python expressions and statements in the interactive programming environment called the shell. In Jupyter Notebook, we will run these in a 'cell'.

### Print Function

We can also force the output of a value by using the **print** function. The simples for would look like this.

    print(<expression>)

You can also write a **print** function that includes two or more expressions separated by commas.

    print(<expression>, ..., <expression>)

```{python}
#statements are interpreted one by one
print ("Hello World")
print ("something else")
print ("2+2")
```

```{python}
#Here are some escape sequences
a = "Hello\aFUGU\aSHRIMP"
b = 'Hello\tFUGU\nSHRIMP' #single quotes work as well 
print (a,b)

#why do you think the output is like this?
#try taking the escape sequences to find out


```
